server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:2001autumn/springcloud-config.git #GitHub的git仓库名字 估计：本地密钥未生成无法使用
          uri: https://github.com/2001autumn/springcloud-config.git #GitHub的git仓库名字
          #搜索目录
          search-paths:
            - springcloud-config
      label: master

#rabbitmq相关配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

#服务器注册到Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

#rabbitmq相关配置，暴露bus刷新配置的断点
management:
  endpoints: #暴露bus刷新配置的断点
    web:
      exposure:
        include: 'bus-refresh'

#bus一次发送，处处生效 cmd动态刷新curl -X POST "http://localhost:3344/actuator/bus-refresh"
#定点destination(服务名+端口号) curl -X POST "http://localhost:3344/actuator/bus-refresh/config-client:3355"