server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:2001autumn/springcloud-config.git #GitHub的git仓库名字 估计：本地密钥未生成无法使用
          uri: https://github.com/2001autumn/springcloud-config.git #GitHub的git仓库名字
          #搜索目录
          search-paths:
            - springcloud-config
      label: master

#服务器注册到Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka